"""Add second price fields to Product model, auto_activate fields to Category model

Revision ID: ffc1532a8e06
Revises: 
Create Date: 2025-02-26 14:18:29.024419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc1532a8e06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Campi per Product model
    try:
        with op.batch_alter_table('product', schema=None) as batch_op:
            batch_op.add_column(sa.Column('price_2', sa.Float(), nullable=True))
            batch_op.add_column(sa.Column('price_2_label', sa.String(length=20), nullable=True))
    except:
        # In caso di errore (se le colonne esistono già), ignora
        pass
        
    # Campi per Category model
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_activate', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('active_days', sa.String(length=100), nullable=True, server_default='0,1,2,3,4,5,6'))
        batch_op.add_column(sa.Column('active_start_time', sa.String(length=5), nullable=True, server_default='00:00'))
        batch_op.add_column(sa.Column('active_end_time', sa.String(length=5), nullable=True, server_default='23:59'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('active_end_time')
        batch_op.drop_column('active_start_time')
        batch_op.drop_column('active_days')
        batch_op.drop_column('auto_activate')
        
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('price_2_label')
        batch_op.drop_column('price_2')
    # ### end Alembic commands ###
